### ISSUE TITLE
Authors of the project, do you have the courage to face this fact?

### ISSUE THREAD

**Issue by pzc163** [mustafaaljadery/llama3v#7]
I've discovered a jaw-dropping fact，it seems that Llama3-V has identical model structures and config files to MiniCPM-Llama3-V 2.5 (https://github.com/OpenBMB/MiniCPM-V), its code is a reformatting of MiniCPM-Llama3-V 2.5.
1. Model Structure & Code
Llama3-V has exactly the same model structure and config file as MiniCPM-Llama3-V 2.5, with only the difference in variable names. Left: MiniCPM-Llama3-V 2.5  Right: Llama3-V
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/7bd3f45e-0339-4edd-b1e8-40aa65a6e590)
Its code appears to be MiniCPM-Llama3-V 2.5's code with some reformatting and variable renaming, including but not limited to image slicing, tokenizer, resampler, and data loading. Just give some examples.
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/b1fde97f-c348-4edb-9453-d5a75a327d4b)
The author of Llama3-V refers to LLaVA-UHD for the architecture, and list difference (on ViT and LLM choice). What the author does not mention is that their specific implementation is identical to MiniCPM-Llama3-V 2.5, which is different from LLaVA-UHD in many ways, such as the spatial schema. Llama3-V also has the same tokenizer as MiniCPM-Llama3-V 2.5, including the special tokens newly defined by MiniCPM-Llama3-V 2.5.
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/bd23c5c4-d32e-4f01-8d33-db8ac2eeceff)
Initially, the author uploaded code that directly imported MiniCPM-V’s code and later changed the name to Llama3-V.
https://huggingface.co/mustafaaljadery/llama3v/commit/3bee89259ecac051d5c3e58ab619e3fafef20ea6
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/1d45564d-dd38-486c-b0b1-b07b5fe9081c)
It seems the author is avoiding fully discussion about MiniCPM-Llama3-V 2.5, even after being prompted by users. 
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/26a5ac52-4808-4ab0-9706-afd387be7100)
I am really shocked by this, it is hard to imagine that the authors of Llama3-V can steal the work of MiniCPM-Llama3-V 2.5 so nakedly, I am really outraged by what you have done! And feel shameful that as students of Stanford could do such a thing!

**Comment by mustafaaljadery** [comment]
This is very false. We used the configs on MiniCPM-llama3 in this repo because you have to have specific configs for running the model using huggingface transformers! Til right now, there are still issues with implementation for it to run on huggingface transformers. There has to be a specific rules, that we haven't used. I tested MiniCPM and their configs worked that's why we used the same configs. Moreover, I've highlighted the architecture is the same but MiniCPM's architecture is from Idefics. SigLIP is from Idefics, same with ideas on projection. We go those from the Idefics paper. LLava UHD is from their lab, and I've highlighted that. Moreover, I've highlighted more about how it's the same architecture, but the architecture is from combined research, how can you say it's MiniCPM. Read the MiniCPM code, literally the code for vision is used from Idefics.

**Comment by pzc163** [comment]
So could you explain why you removed the repo of llama3-V on Huggingface right now?
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/a8294022-fdc7-42e2-ad5e-76f21481c659)

**Comment by mustafaaljadery** [comment]
<img width="695" alt="Screenshot 2024-06-01 at 10 58 00 AM" src="https://github.com/mustafaaljadery/llama3v/assets/68826650/366bf25b-7af2-4463-a4bc-771d972fa964">

I made it private to fix the inference. The inference still doesn't work because you have to have specific config for it to work with huggingface transformers. The MiniCPM-LLama3 config that I tried to use doesn't work with the model! People were downloading a model and seeing it doesn't work. That's why I made it private so people don't download while I fix the issue.

**Comment by pzc163** [comment]
I'm very curious how they accessed the tokenizer before released

> <img alt="Screenshot 2024-06-01 at 10 58 00 AM" width="695" src="https://private-user-images.githubusercontent.com/68826650/335819397-366bf25b-7af2-4463-a4bc-771d972fa964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjYyMzksIm5iZiI6MTcxNzI2NTkzOSwicGF0aCI6Ii82ODgyNjY1MC8zMzU4MTkzOTctMzY2YmYyNWItN2FmMi00NDYzLWE0YmMtNzcxZDk3MmZhOTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4MTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNjIwZjgxYTdhYTUzNThhYjU1MDM1MjE3MjVlNmQ1ZmZjOWExZjJhOGQ4ODMyM2FhMjEzZjVhYmY2NWJmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b126QAdPzSy7T8zkiz6URRvPghFzRAgN4OlQYrVwZyk">
> I made it private to fix the inference. The inference still doesn't work because you have to have specific config for it to work with huggingface transformers. The MiniCPM-LLama3 config that I tried to use doesn't work with the model! People were downloading a model and seeing it doesn't work. That's why I made it private so people don't download while I fix the issue.

You says that you just use MiniCPM-Llama3-V 2.5's tokenizer. But also claim to have started the work before MiniCPM-Llama3-V 2.5's release. I'm very curious about how you accessed the tokenizer before its released.
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/a2234ac5-60f1-4a80-9371-c782d487244c)
![image](https://github.com/mustafaaljadery/llama3v/assets/105222039/35c9450a-17a0-442d-8edd-761914dd544c)

**Comment by mustafaaljadery** [comment]
It's wrong I thought the tokenizer would be from here: https://huggingface.co/openbmb/MiniCPM-V-2/blob/main/tokenizer.json. Before Llama3 MiniCPM released a smaller model that was really good: https://github.com/OpenBMB/MiniCPM-V As I have stated the MiniCPM work is amazing. They make amazing vision models, and I learned a lot from them when building. I thought the Llama3 would be Llama3 tokenizer + old MiniCPM additional tokens that's why. But again, the model didn't run, there is a bunch of stuff that is different.

**Comment by mustafaaljadery** [comment]
Now that I've shared everything with you, your comment is unprofessional and without merit. I'm happy to add you to codebases so you can see the logs, I will also be releasing the training and dataset this week after some clean up + fix the inference to put the model back up. Feel free to email me: aljadery@usc.edu with any info you want about the model or be added anywhere. I will be removing the issue.
